spaceone-dev/console-core-lib

.babelrc
package-lock.json
package.json
src/component-util/dynamic-layout/index.ts
src/component-util/query-search/index.ts
src/component-util/toolbox/index.ts
src/index.ts
src/query/config.ts
src/query/helper.ts
src/query/index.ts
src/space-connector/api.ts
src/space-connector/helper.ts
src/space-connector/index.ts
tsconfig.json

- 빌드 시 babel과 tsc 커맨드 전부 사용
- tsc-alias 라이브러리 사용하여 빌드 시 절대경로를 상대경로로 변경
```
"build": "npm run babel && npm run tsc",
"babel": "babel src --out-dir dist --extensions \".ts\" --source-maps inline --copy-files",
"tsc": "tsc --project tsconfig.json && tsc-alias -p tsconfig.json"
```

feat: add tsc-alias and edit build script

---

src/index.ts

fix: fix durationFormatter

---

package.json

build:watch script 수정 및 tsc:watch script 추가

fix: npm build:watch script

---

.eslintrc.js
package-lock.json
package.json
src/space-connector/api.ts
src/space-connector/index.ts

chore: fix way of using lodash in space-connector

---

src/space-connector/api.ts
src/space-connector/index.ts

토큰 연장 작업
토큰 연장을 위한 check Token 함수의 조건을 수정하였습니다.

fix: token check condition

---

src/query/index.ts
src/space-connector/helper.ts

Add filterOr to QueryHelper
https://pyengine.atlassian.net/browse/CLOUD-5027
QueryHelper에 setOrFilter(), addOrFilter(), get orFilters() 추가 했습니다.

feat: add filterOr to QueryHelper

---

src/space-connector/api.ts

refresh token 로직
인스턴스의 멤버 변수가 아닌 로컬스토리지에서 가져온 refresh token을 이용하도록 함

fix: refresh token logic

---

src/component-util/dynamic-layout/index.ts

restrict to use operator =. != when search item is enum type or reference.

feat: add operators to makeQuerySearchPropsWithSearchSchema

---

package.json
src/component-util/dynamic-layout/type.ts
src/component-util/query-search/index.ts
src/component-util/toolbox/index.ts
src/index.ts
src/query/config.ts
src/query/index.ts
src/query/type.ts
src/space-connector/api.ts
src/space-connector/index.ts
src/space-connector/type.ts

- iso8601Formatter 의 마지막 파라미터 format을 추가하여, 다른 포맷으로 보여주고 싶은 경우에도 사용할 수 있도록 하였습니다.
- dayjs, vue composition-api dependency가 dev dependency로 되어있어, 이를 다시 dependencies 에 추가하고, peer dependency에도 추가하였습니다.
- duration util 함수가 제대로 동작하지 않을 것으로 보이는 부분이 있어 수정하였습니다.
- vue composition-api 는 console core lib 에는 사용되지 않는 것이 좋을 것 같습니다. 추후 이를 리팩토링하는 과정이 필요할 것으로 보입니다.
- duration 은 durationFormatter 함수 내부에서 함수가 만들어지고, 단 한 번만 사용됩니다. duration을 함수로 만들지 않고 그 로직을 durationFormatter 함수 내부에서 처리하거나, duration 함수를 바깥으로 빼는 것이 어떨지 의견 드립니다.

feat: add format to iso8601Formatter

---

.eslintrc.js
src/index.ts
src/query/helper.ts
src/query/index.ts
src/space-connector/helper.ts
src/space-connector/type.ts

- fix lint rule
- make functions in query helper pure

refactor: make functions pure in query helper and fix variable convention lint rule

---

src/space-connector/api.ts

chore: remove error message

---

src/query/index.ts

fix: type error

---

src/index.ts

- Duration 에 마이너스가 표시될경우 'now'로 노출 되도록 수정

fix: duration function bugs

---

src/space-connector/api.ts
src/space-connector/constants.ts
src/space-connector/error.ts
src/space-connector/index.ts
src/space-connector/type.ts

error class와 error handler를 만들어 axios interceptor에 적용하였습니다.

feat: add error class, error handler

---

.eslintrc.js
.github/workflows/review.yml
.husky/commit-msg
.husky/pre-commit
.lintstagedrc.js
commitlint.config.js
package-lock.json
package.json
src/component-util/dynamic-layout/index.ts
src/component-util/query-search/index.ts
src/component-util/query-search/type.ts
src/index.ts
src/query/config.ts
src/query/index.ts
src/sample.spec.ts
src/space-connector/api.ts
src/space-connector/index.ts
src/space-connector/type.ts

- review workflow 를 추가하였습니다. (lint, test, build)
- test environment를 console api repo 와 동일하게 구성하였습니다. 그리고 샘플코드를 추가하였습니다.
- pre commit, commit msg husky hook을 추가하였습니다. (design system레포와 동일)

ci: add review workflow, set test env, and git hooks

---

src/index.ts
src/space-connector/api.ts
src/space-connector/error.ts

feat: remove unused util and log error for testing

---

src/index.ts

fix: lint error

---

package.json

fix: update semantic release script

---

package-lock.json
package.json

feat: update axios version

---

package.json

fix: fix typo in semantic release script

---

.github/workflows/review.yml
.github/workflows/workflow.yml

fix: update workflow node versions

---

package.json

fix: update semantic release script to skip husky

---

package-lock.json
package.json
src/space-connector/api.ts

build: update design system version

---

.github/workflows/workflow.yml

fix: workflow file

---

src/index.ts

numberFormatter에 digits 인자를 추가하여 소숫점 자리를 조정가능하도록 했습니다.

fix: add digits props to numberFormatter

---

.github/workflows/workflow.yml
package-lock.json
package.json
src/index.ts

feat: add getNumberFromString helper

---

package-lock.json
package.json
src/component-util/dynamic-layout/index.ts

fix: update design system version

---

src/space-connector/index.ts

- mock info가 주입되는 경우에만  mock client를 생성하도록 추가
-

feat: add SpaceConnector mock client

---

src/space-connector/index.ts

fix: fix bug of api mock handler in space connector

---

package-lock.json
package.json
src/component-util/dynamic-layout/field-schema.ts
src/component-util/dynamic-layout/index.ts
src/component-util/dynamic-layout/layout-schema.ts
src/component-util/dynamic-layout/type.ts
src/component-util/query-search/index.ts
src/component-util/query-search/type.ts
src/space-connector/helper.ts

build: remove design system from dependency

---

src/component-util/toolbox/index.ts
src/space-connector/helper.ts
src/space-connector/type.ts

multi sort를 위한 함수를 추가했습니다. 
sort를 rest로 풀어서도 넣고, addSort 방식으로 추가하는것처럼도 해봤는데.. 직접 콘솔에 넣었을때 가장 쉬운 방향으로 구현했습니다! 
key에다가 attach 시키는 게 아니고 keys라는 다른 키값에 또 넣는거라..!

feat: add multi sort function

---

package-lock.json
package.json

build: add rimraf to dev dependency

---

src/space-connector/api.ts
src/space-connector/index.ts

종민님과 함께 session 연장 문제를 수정하였습니다.
자세한 트러블 슈팅 과정은 노션에다가 추후 적겠습니다!

fix: session expiration issue

---

src/space-connector/index.ts

feat: add after callback to api handler in space connector

---

package-lock.json
package.json
src/index.ts
src/space-connector/api.ts
tsconfig.json

Add refresh logic to authentication error handler

fix: authentication error handling

---

src/space-connector/api.ts
src/space-connector/index.ts

fix: return value

---

package-lock.json
package.json

Typescript 버전 업데이트 후 axios의 error 타입과 맞지 않아 에러핸들링이 제대로 되지 않았습니다.
axios에서 2.2.0~2.5.0 동안 타입이 몇 번 수정되어 해당 사항을 반영하여 버전업했더니 문제가 해결되었습니다.

fix: update axios version for changed error type

---

src/query/helper.ts

fix: make query helper datetime converter add filters properly

---

src/space-connector/index.ts

fix: add afterCall callback to non mock api handler in space connector

---

src/space-connector/api.ts

fix: refresh logic

---

src/index.ts

fix: add minUnit to byteFormatter

---

src/query/index.ts

fix: separate `setReference` from init method in QueryHelper

---

src/component-util/query-search/type.ts
src/query/config.ts

feat: change regex operator ($ -> ~)

---

.eslintrc.js
package-lock.json
package.json
src/component-util/dynamic-layout/index.ts
src/component-util/query-search/index.ts
src/component-util/toolbox/index.ts
src/index.ts
src/query/config.ts
src/query/helper.ts
src/query/index.ts
src/sample.spec.ts
src/space-connector/api.ts
src/space-connector/error.ts
src/space-connector/index.ts

style: apply eslint-plugin-import
